<a href="https://colab.research.google.com/github/mfernandezzz/Data-Analysis-Projects/blob/main/demographic_data_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Demographic Data Analyzer**

In this challenge you must analyze demographic data using Pandas. You are given a dataset of demographic data that was extracted from the 1994 Census database. Here is a sample of what the data looks like:

|    |   age | workclass        |   fnlwgt | education   |   education-num | marital-status     | occupation        | relationship   | race   | sex    |   capital-gain |   capital-loss |   hours-per-week | native-country   | salary   |
|---:|------:|:-----------------|---------:|:------------|----------------:|:-------------------|:------------------|:---------------|:-------|:-------|---------------:|---------------:|-----------------:|:-----------------|:---------|
|  0 |    39 | State-gov        |    77516 | Bachelors   |              13 | Never-married      | Adm-clerical      | Not-in-family  | White  | Male   |           2174 |              0 |               40 | United-States    | <=50K    |
|  1 |    50 | Self-emp-not-inc |    83311 | Bachelors   |              13 | Married-civ-spouse | Exec-managerial   | Husband        | White  | Male   |              0 |              0 |               13 | United-States    | <=50K    |
|  2 |    38 | Private          |   215646 | HS-grad     |               9 | Divorced           | Handlers-cleaners | Not-in-family  | White  | Male   |              0 |              0 |               40 | United-States    | <=50K    |
|  3 |    53 | Private          |   234721 | 11th        |               7 | Married-civ-spouse | Handlers-cleaners | Husband        | Black  | Male   |              0 |              0 |               40 | United-States    | <=50K    |
|  4 |    28 | Private          |   338409 | Bachelors   |              13 | Married-civ-spouse | Prof-specialty    | Wife           | Black  | Female |              0 |              0 |               40 | Cuba             | <=50K    |

You must use Pandas to answer some questions about this dataset.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df = pd.read_csv('/content/adult.csv')
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [5]:
df.shape #rows, columns

(32560, 15)

In [6]:
#assign name columns to the dataset
col_names = [
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education-num',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'capital-gain',
    'capital-loss',
    'hours-per-week',
    'native-country',
    'salary'
    ]

df.columns = col_names
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

**How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels (race column)**

In [7]:
#get a table with the race and the quantity of people for each race
df_race_count = df['race'].value_counts()
df_race_count

race
White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [8]:
#create the Pandas series
df_race_people = pd.Series([27815, 3124, 1039, 311, 271]) #numeric values, represent the quantity of people per race
df_race_people.index = [ #assign index to the Pandas series
    'White',
    'Black',
    'Asian-Pac-Islander',
    'Amer-Indian-Eskimo',
    'Other'
]
df_race_people.name = 'Quantity of people per race'
df_race_people

White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: Quantity of people per race, dtype: int64

In [9]:
race_percentage = pd.DataFrame({
    'race': ['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other'],
    'quantity': [27815, 3124, 1039, 311, 271]
}, columns = ['race', 'quantity'])
race_percentage

                 race  quantity
0               White     27815
1               Black      3124
2  Asian-Pac-Islander      1039
3  Amer-Indian-Eskimo       311
4               Other       271

In [10]:
race_percentage['percentage'] = round(race_percentage['quantity'] * 100 / 32561, 2)
race_percentage

                 race  quantity  percentage
0               White     27815       85.42
1               Black      3124        9.59
2  Asian-Pac-Islander      1039        3.19
3  Amer-Indian-Eskimo       311        0.96
4               Other       271        0.83

**What is the average age of men?**

In [11]:
#locate the column sex with the value 'Male' and the columns 'age', get the mean value of ages
average_age_men = df.loc[df['sex'].str.contains('Male'), 'age'].mean()
round(average_age_men)

39

**What is the percentage of people who have a Bachelor's degree?**

In [12]:
#obtain the name of the educational levels and the quantity of persons respectively
education = df['education'].value_counts()
education

education
HS-grad         10501
Some-college     7291
Bachelors        5354
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [13]:
#create a new dataframe with the results obtained before
df_education = pd.DataFrame({
    'education level': [
        'HS-grad',
        'Some-college',
        'Bachelors',
        'Masters',
        'Assoc-voc',
        '11th',
        'Assocc-acdm',
        '10th',
        '7th-8th',
        'Prof-school',
        '9th',
        '12th',
        'Doctorate',
        '5th-6th',
        '1st-4th',
        'Preschool'
    ],
    'quantity': [10501, 7291, 5354, 1723, 1382, 1175, 1067, 933, 646, 576, 514, 433, 413, 333, 168, 51]
}, columns = ['education level', 'quantity'])
df_education

   education level  quantity
0          HS-grad     10501
1     Some-college      7291
2        Bachelors      5354
3          Masters      1723
4        Assoc-voc      1382
5             11th      1175
6      Assocc-acdm      1067
7             10th       933
8          7th-8th       646
9      Prof-school       576
10             9th       514
11            12th       433
12       Doctorate       413
13         5th-6th       333
14         1st-4th       168
15       Preschool        51

In [14]:
#the quantity of bachelors
bachelors = df_education.loc[df_education['education level'].str.contains('Bachelors'), 'quantity']
#total people registered in the dataframe
total = df_education['quantity'].sum()
#percentage of bachelors in the dataframe
bach_percentage = (bachelors * 100) / total
round(bach_percentage, 2)

2    16.44
Name: quantity, dtype: float64

In [15]:
#assign a new column with the percentages of people per education level
df_education['percentages'] = round(df_education['quantity'] * 100 / total, 2)
df_education

   education level  quantity  percentages
0          HS-grad     10501        32.25
1     Some-college      7291        22.39
2        Bachelors      5354        16.44
3          Masters      1723         5.29
4        Assoc-voc      1382         4.24
5             11th      1175         3.61
6      Assocc-acdm      1067         3.28
7             10th       933         2.87
8          7th-8th       646         1.98
9      Prof-school       576         1.77
10             9th       514         1.58
11            12th       433         1.33
12       Doctorate       413         1.27
13         5th-6th       333         1.02
14         1st-4th       168         0.52
15       Preschool        51         0.16

**What percentage of people with advanced education (Bachelors, Masters, Doctorate) make more than 50k?**

In [16]:
#the first step is known the quantity of people have a salary above 50k
salary_ranges = df['salary'].value_counts()
salary_ranges

salary
<=50K    24719
>50K      7841
Name: count, dtype: int64

In [17]:
#quantity of Bachelors with a salary above 50k
bachelors = df.loc[df['education'].str.contains('Bachelors'), 'salary'].value_counts()
bachelors

salary
<=50K    3133
>50K     2221
Name: count, dtype: int64

In [18]:
#quantity of Masters with a salary above 50k
masters = df.loc[df['education'].str.contains('Masters'), 'salary'].value_counts()
masters

salary
>50K     959
<=50K    764
Name: count, dtype: int64

In [19]:
#quantity of Doctorates with a salary above 50k
doctorate = df.loc[df['education'].str.contains('Doctorate'), 'salary'].value_counts()
doctorate

salary
>50K     306
<=50K    107
Name: count, dtype: int64

In [20]:
#individuals with a salary above 50k
high_salary_total = 7841
#individuals with a high education level and a salary above 50k
high_ed_lvl = 2221 + 959 + 306
#percentage of individuals with a high level education and a salary above 50k
percentage = (high_ed_lvl * 100) / high_salary_total
round(percentage, 2)

44.46

**What percentage of people without advanced education make more than >50k?**

In [21]:
#total of individuals with a salary above 50k - individuals with high level education
low_ed_lvl = high_salary_total - high_ed_lvl
percentage_low = (low_ed_lvl * 100) / high_salary_total
round(percentage_low, 2)

55.54

**What is the minimum and maximum number of hours a person works per week?**

In [22]:
df['hours-per-week'].min()

1

In [23]:
df['hours-per-week'].max()

99

**What percentage of people who work the minimum hours per week have a salary of more than 50k?**

In [24]:
#this query obtain some hours per week and the count of people that have a salary >50k working the respective hours
hours_quantity = df.loc[df['salary'].str.contains('>50K'), 'hours-per-week'].value_counts()
hours_quantity.head(5)

hours-per-week
40    3247
50    1276
45     685
60     648
55     323
Name: count, dtype: int64

In [25]:
#this query verify the result obtained before
example = df.loc[df['hours-per-week'] == 40, 'salary'].value_counts()
example

salary
<=50K    11969
>50K      3247
Name: count, dtype: int64

In [26]:
#quantity of people that works the minimum hours per week and have a salary >50k
min_hours = df.loc[df['hours-per-week'] == 1, 'salary'].value_counts()
min_hours

salary
<=50K    18
>50K      2
Name: count, dtype: int64

In [27]:
salary_ranges = df['salary'].value_counts()
salary_ranges

salary
<=50K    24719
>50K      7841
Name: count, dtype: int64

In [28]:
#percentage of individuals working the minimum of hours per week with a salary >50k
min_hours_percentage = (2 * 100) / 7841
round(min_hours_percentage, 2)

0.03

In [29]:
#percentage of people working 40 hours per week with a salary >50k (only for verify)
exam_percentage = (3247 * 100) / 7841
round(exam_percentage, 2)

41.41

**What country has the highest percentage of people that earn >50k and what is that percentage?**

In [30]:
#all the countries in the df
countries = df['native-country'].unique()
countries

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [31]:
#all the countries where individuals have a salary >50k
countries_high_salary = df['native-country'].loc[df['salary'].str.contains('>50K')].unique()
countries_high_salary

array([' United-States', ' India', ' ?', ' South', ' Honduras', ' Canada',
       ' Iran', ' Mexico', ' Cambodia', ' Thailand', ' Taiwan',
       ' Portugal', ' England', ' China', ' Philippines', ' Jamaica',
       ' Germany', ' Japan', ' Italy', ' Dominican-Republic', ' Cuba',
       ' Greece', ' Peru', ' Guatemala', ' El-Salvador', ' France',
       ' Vietnam', ' Poland', ' Puerto-Rico', ' Ireland', ' Yugoslavia',
       ' Columbia', ' Haiti', ' Hong', ' Ecuador', ' Nicaragua',
       ' Trinadad&Tobago', ' Hungary', ' Scotland', ' Laos'], dtype=object)

In [32]:
#all the countries with individuals with a high salary
countries_high_salary = df['native-country'].loc[df['salary'].str.contains('>50K')].value_counts()
countries_high_salary

native-country
United-States         7171
?                      146
Philippines             61
Germany                 44
India                   40
Canada                  39
Mexico                  33
England                 30
Cuba                    25
Italy                   25
Japan                   24
Taiwan                  20
China                   20
Iran                    18
South                   16
Poland                  12
France                  12
Puerto-Rico             12
Jamaica                 10
El-Salvador              9
Greece                   8
Cambodia                 7
Hong                     6
Yugoslavia               6
Vietnam                  5
Ireland                  5
Portugal                 4
Ecuador                  4
Haiti                    4
Scotland                 3
Guatemala                3
Thailand                 3
Hungary                  3
Columbia                 2
Peru                     2
Dominican-Republic       2
Trinadad&Tobago          2
Nicaragua                2
Laos                     2
Honduras                 1
Name: count, dtype: int64

In [33]:
#create a new Pandas dataframe
df_countries_high_salary = pd.DataFrame({
    'country': [
        'United States',
        'Rest of the world',
        'Philippines',
        'Germany',
        'India',
        'Canada',
        'Mexico',
        'England',
        'Cuba',
        'Italy',
        'Japan',
        'Taiwan',
        'China',
        'Iran',
        'South',
        'Poland',
        'France',
        'Puerto Rico',
        'Jamaica',
        'El Salvador',
        'Greece',
        'Cambodia',
        'Hong Kong',
        'Yugoslavia',
        'Vietnam',
        'Ireland',
        'Portugal',
        'Ecuador',
        'Haiti',
        'Scotland',
        'Guatemala',
        'Thailand',
        'Hungary',
        'Colombia',
        'Peru',
        'Dominican Republic',
        'Trinidad and Tobago',
        'Nicaragua',
        'Laos',
        'Honduras'
  ],
    'quantity': [7171, 146, 61, 44, 40, 39, 33, 30, 25, 25, 24, 20, 20, 18, 16, 12, 12, 12, 10, 9, 8, 7, 6, 6, 5, 5, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 1]
}, columns = ['country', 'quantity'])
df_countries_high_salary

                country  quantity
0         United States      7171
1     Rest of the world       146
2           Philippines        61
3               Germany        44
4                 India        40
5                Canada        39
6                Mexico        33
7               England        30
8                  Cuba        25
9                 Italy        25
10                Japan        24
11               Taiwan        20
12                China        20
13                 Iran        18
14                South        16
15               Poland        12
16               France        12
17          Puerto Rico        12
18              Jamaica        10
19          El Salvador         9
20               Greece         8
21             Cambodia         7
22            Hong Kong         6
23           Yugoslavia         6
24              Vietnam         5
25              Ireland         5
26             Portugal         4
27              Ecuador         4
28                Haiti         4
29             Scotland         3
30            Guatemala         3
31             Thailand         3
32              Hungary         3
33             Colombia         2
34                 Peru         2
35   Dominican Republic         2
36  Trinidad and Tobago         2
37            Nicaragua         2
38                 Laos         2
39             Honduras         1

In [34]:
#verify if the total individuals registered in the DataFrame are equal to the total of individuals with a salary >50k.
df_countries_high_salary['quantity'].sum()

np.int64(7841)

In [35]:
#verify if the total rows in the dataframe corresponds to the total countries with individuals with a salary >50k
df_countries_high_salary.shape

(40, 2)

In [36]:
#create a new column with the percentage of individuals living in his respective country and a salary >50k
#obtain the percentage of individuals with a salary >50k and the respective country
df_countries_high_salary['percentage'] = round(df_countries_high_salary['quantity'] * 100 / 7841, 2)
df_countries_high_salary.head(1)

         country  quantity  percentage
0  United States      7171       91.46

**Identify the most popular occupation for those who earn >50k in India.**

In [37]:
#obtain all the occupations
occupations = df['occupation'].unique()
len(occupations)

15

In [38]:
#get the quantity of individuals living in India (number of rows)
india_ppl = df.loc[df['native-country'].str.contains('India')]
india_ppl.shape

(100, 15)

In [39]:
#get the quantity of individuals living in India per range salary
ppl_india_salary = df.loc[df['native-country'].str.contains('India'), 'salary'].value_counts()
ppl_india_salary

salary
<=50K    60
>50K     40
Name: count, dtype: int64

In [40]:
#get the most popular occupation for those who live in India and have a salary >50k
ppl_india_high_salary = df['occupation'].loc[df['native-country'].str.contains('India') & df['salary'].str.contains('>50K')].value_counts()
ppl_india_high_salary.head(1)

occupation
Prof-specialty    25
Name: count, dtype: int64