<a href="https://colab.research.google.com/github/mfernandezzz/Data-Analysis-Projects/blob/main/demographic_data_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Demographic Data Analyzer**

In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [96]:
df = pd.read_csv('/content/adult.csv')
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [97]:
df.shape

(32560, 15)

In [98]:
nulls_count = df.isnull().sum()
nulls_count[nulls_count > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [99]:
df.columns

Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

Assign name columns to the dataset

In [100]:
col_names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain',
             'capital-loss', 'hours-per-week', 'native-country', 'salary']

df.columns = col_names
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

The previous names of columns correspond to a row of data that was missing

In [101]:
mask = (df['workclass'].str.contains('State-gov')) & (df['fnlwgt'] == 77516)
df.loc[mask]

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, salary]
Index: []

Add the missing row of data to the DataFrame

In [102]:
missed_row = {'age': 39, 'workclass': 'State-gov', 'fnlwgt': 77516, 'education': 'Bachelors', 'education-num': 13, 'marital-status': 'Never-married',
       'occupation': 'Adm-clerical', 'relationship': 'Not-in-family', 'race': 'White', 'sex': 'Male', 'capital-gain': 2174, 'capital-loss': 0,
       'hours-per-week': 40, 'native-country': 'United-States', 'salary': '<=50K'}
df = pd.concat([df, pd.DataFrame([missed_row])], ignore_index=True)

In [103]:
# to add multiple rows
# rows = [
#     {"col1": 10, "col2": "abc"},
#     {"col1": 20, "col2": "def"},
# ]
# df = pd.concat([df, pd.DataFrame(rows)], ignore_index=True)

In [104]:
mask = (df['workclass'].str.contains('State-gov')) & (df['fnlwgt'] == 77516)
df.loc[mask]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
32560,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K

In [105]:
df.shape

(32561, 15)

In [106]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

In [107]:
df['education'].unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th', 'Bachelors'], dtype=object)

In [108]:
columns_strings = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'salary']
for col in columns_strings:
  df[col] = df[col].astype(str).str.strip()

In [109]:
df['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [110]:
df.duplicated().sum()

np.int64(24)

In [111]:
mask_dupples = df.duplicated()
show_duplicated = df.loc[mask_dupples]
show_duplicated.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
4880,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
5103,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
9170,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
11630,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
13083,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K

In [112]:
df = df.drop_duplicates()

In [113]:
df.shape

(32537, 15)

In [114]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

**How many people of each race are represented in this dataset? Create a DataFrame with race names, quantity and percentage of people per race.**

In [115]:
df_race_people = pd.DataFrame(df['race'].value_counts()).reset_index()
df_race_people.rename(columns={'count': 'individuals'}, inplace=True)
df_race_people['%'] = round((df_race_people['individuals'] / df_race_people['individuals'].sum()) * 100, 2)
df_race_people

                 race  individuals      %
0               White        27795  85.43
1               Black         3122   9.60
2  Asian-Pac-Islander         1038   3.19
3  Amer-Indian-Eskimo          311   0.96
4               Other          271   0.83

In [116]:
race_percentage = pd.DataFrame({
    'race': ['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other'],
    'quantity': [27795, 3122, 1038, 311, 271]
}, columns = ['race', 'quantity'])

race_percentage['%'] = round(race_percentage['quantity'] * 100 / df.shape[0], 2)
race_percentage

                 race  quantity      %
0               White     27795  85.43
1               Black      3122   9.60
2  Asian-Pac-Islander      1038   3.19
3  Amer-Indian-Eskimo       311   0.96
4               Other       271   0.83

In [117]:
# race_series = pd.Series(df['race'].value_counts())
# race_series.name = 'Quantity of people by race'
# race_series.index.name = 'Race'
# race_series

In [118]:
# df_race_people = pd.Series([27815, 3124, 1039, 311, 271])
# df_race_people.index = [
#     'White',
#     'Black',
#     'Asian-Pac-Islander',
#     'Amer-Indian-Eskimo',
#     'Other'
# ]
# df_race_people.name = 'Quantity of people per race'
# df_race_people.index.name = 'Race'
# df_race_people

**What is the average age of men?**

In [119]:
average_age_men = df.loc[df['sex'].str.contains('Male'), 'age'].mean()
f'Average age of men: {round(average_age_men)} years old'

'Average age of men: 39 years old'

In [120]:
mask_male = df['sex'].str.contains('Male')
df_males = df.loc[mask_male][['age']]

In [121]:
df_males['age'].median()

38.0

**What is the percentage of people who have a Bachelor's degree?**

In [122]:
df_education = pd.DataFrame(df['education'].value_counts()).reset_index()
df_education.rename(columns={'count': 'individuals'}, inplace=True)
df_education['%'] = round((df_education['individuals'] / df_education['individuals'].sum()) * 100, 2)
df_education

       education  individuals      %
0        HS-grad        10494  32.25
1   Some-college         7282  22.38
2      Bachelors         5353  16.45
3        Masters         1722   5.29
4      Assoc-voc         1382   4.25
5           11th         1175   3.61
6     Assoc-acdm         1067   3.28
7           10th          933   2.87
8        7th-8th          645   1.98
9    Prof-school          576   1.77
10           9th          514   1.58
11          12th          433   1.33
12     Doctorate          413   1.27
13       5th-6th          332   1.02
14       1st-4th          166   0.51
15     Preschool           50   0.15

In [123]:
bachelors_data = df_education.loc[df_education['education'] == 'Bachelors', ['individuals', '%']]
bachelors_data

   individuals      %
2         5353  16.45

In [124]:
print(f'The percentage of people with a Bachelors degree is {bachelors_data.iloc[0, 1]}%')
print(f'The amount of individuals with a Bachelors degree is {bachelors_data.iloc[0, 0]}')

The percentage of people with a Bachelors degree is 16.45%
The amount of individuals with a Bachelors degree is 5353

In [125]:
bachelors = df_education.loc[df_education['education'].str.contains('Bachelors'), ['individuals', '%']]
bachelors

   individuals      %
2         5353  16.45

**What percentage of people with advanced education (Bachelors, Masters, Doctorate) make more than 50k?**

Filter out by education levels and salary level

In [126]:
mask_adv_ed = ((df['education'] == 'Bachelors') | (df['education'] == 'Masters') | (df['education'] == 'Doctorate')) & (df['salary'] == '>50K')
df_adv_ed = df.loc[mask_adv_ed]
df_adv_ed.shape

(3486, 15)

Total of individuals with a salary >50k

In [127]:
df['salary'].value_counts()

salary
<=50K    24698
>50K      7839
Name: count, dtype: int64

In [128]:
percentage = (df_adv_ed.shape[0] / 7839) * 100
f'The percentage of people with advanced education and a salary >50k is {round(percentage, 2)}%'

'The percentage of people with advanced education and a salary >50k is 44.47%'

In [129]:
# bachelors = df.loc[df['education'].str.contains('Bachelors'), 'salary'].value_counts()
# bachelors

**What percentage of people without advanced education make more than 50k?**

In [130]:
low_ed_level = 7839 - df_adv_ed.shape[0]
percentage_two = round((low_ed_level / 7839) * 100, 2)
f'The percentage of people without advanced education and a salary >50k is {percentage_two}%'

'The percentage of people without advanced education and a salary >50k is 55.53%'

**What is the minimum and maximum number of hours a person works per week?**

In [131]:
print(f'The minimum hours a person works per week is {df['hours-per-week'].min()} hours.')
print(f'The maximum hours a person works per week is {df['hours-per-week'].max()} hours.')

The minimum hours a person works per week is 1 hours.
The maximum hours a person works per week is 99 hours.

**Obtain the education level and the quantity of individuals who works the minimum and maximum hours per week respectively**

In [132]:
df.loc[df['hours-per-week'] == 1, 'education'].value_counts()

education
HS-grad         7
Assoc-voc       3
10th            3
Some-college    3
Doctorate       1
9th             1
Masters         1
Assoc-acdm      1
Name: count, dtype: int64

In [133]:
df.loc[df['hours-per-week'] == 99, 'education'].value_counts()

education
HS-grad         18
Some-college    14
Bachelors       10
Doctorate        7
Masters          7
7th-8th          7
Prof-school      6
10th             5
Assoc-voc        4
Assoc-acdm       4
9th              1
11th             1
12th             1
Name: count, dtype: int64

**What percentage of people who work the minimum hours per week have a salary of more than 50k?**

Hours per week and the count of people that have a salary >50k working the respective hours

In [134]:
df.loc[df['salary'].str.contains('>50K'), 'hours-per-week'].value_counts().head()

hours-per-week
40    3246
50    1276
45     685
60     648
55     323
Name: count, dtype: int64

In [135]:
#example
df.loc[df['hours-per-week'] == 40, 'salary'].value_counts()

salary
<=50K    11958
>50K      3246
Name: count, dtype: int64

Individuals that works the minimum hours per week and have a salary >50k

In [136]:
df.loc[df['hours-per-week'] == 1, 'salary'].value_counts()

salary
<=50K    18
>50K      2
Name: count, dtype: int64

In [137]:
min_hours_mask = (df['hours-per-week'] == 1) & (df['salary'].str.contains('>50K'))
df.loc[min_hours_mask]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
188,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K
20071,65,?,76043,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,1,United-States,>50K

In [138]:
salary_ranges = df['salary'].value_counts()
salary_ranges

salary
<=50K    24698
>50K      7839
Name: count, dtype: int64

In [139]:
min_hours_percentage = (2 * 100) / 7839
f'Percentage of people that work the minimum hours and have a salary >50k: {round(min_hours_percentage, 2)}%'

'Percentage of people that work the minimum hours and have a salary >50k: 0.03%'

**What percentage of people who works the maximum hours per week have a salary above 50k?**

In [140]:
df.loc[df['hours-per-week'] == 99, 'salary'].value_counts()

salary
<=50K    60
>50K     25
Name: count, dtype: int64

In [141]:
max_hours_mask = (df['hours-per-week'] == 99) & (df['salary'].str.contains('>50K'))
# df.loc[max_hours_mask].shape[0]
df_max_hours = df.loc[max_hours_mask]
df_max_hours.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
934,37,Private,176900,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,99,United-States,>50K
1171,25,Private,404616,Masters,14,Married-civ-spouse,Farming-fishing,Not-in-family,White,Male,0,0,99,United-States,>50K
1886,55,Self-emp-not-inc,184425,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,>50K
3577,37,Self-emp-inc,382802,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,99,United-States,>50K
4440,43,Self-emp-inc,286750,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,99,United-States,>50K

In [142]:
df_max_hours['education'].value_counts()

education
Some-college    6
HS-grad         5
Doctorate       3
Prof-school     3
Bachelors       3
Masters         2
7th-8th         1
Assoc-voc       1
Assoc-acdm      1
Name: count, dtype: int64

In [143]:
max_hours_percentage = (25 * 100) / 7839
f'Percentage of individuals working the maximum hours and have a salary >50k: {round(max_hours_percentage, 2)}%'

'Percentage of individuals working the maximum hours and have a salary >50k: 0.32%'

In [144]:
# percentage of people working 40 hours per week with a salary >50k (only for verify)
exam_percentage = (3246 * 100) / 7839
f'Percentage of individuals that works 40 hours per week and have a salary above 50k: {round(exam_percentage, 2)}%'

'Percentage of individuals that works 40 hours per week and have a salary above 50k: 41.41%'

**What country has the highest percentage of people that earn >50k and what is that percentage?**

In [145]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [146]:
df_high_salary = pd.DataFrame(df.loc[df['salary'].str.contains('>50K'), 'native-country'].value_counts()).reset_index()
df_high_salary.rename(columns={'count': 'individuals'}, inplace=True)
df_high_salary['%'] = round((df_high_salary['individuals'] / df_high_salary['individuals'].sum()) * 100, 2)
df_high_salary.head(1)

  native-country  individuals      %
0  United-States         7169  91.45

In [147]:
f'The country with the highest percentage of people with a salary above 50K is {df_high_salary.iloc[0, 0]}'

'The country with the highest percentage of people with a salary above 50K is United-States'

**Identify the most popular occupation for those who earn >50k in India.**

In [148]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [149]:
popular_occupation_india = df.loc[(df['salary'].str.contains('>50K') & (df['native-country'].str.contains('India'))), 'occupation'].value_counts().idxmax()
f'The most popular occupation for those who earn >50K in India is {popular_occupation_india}.'

'The most popular occupation for those who earn >50K in India is Prof-specialty.'

Individuals living in India

In [150]:
df.loc[df['native-country'] == 'India'].shape[0]

100

Individuals living in India by range salary

In [151]:
df.loc[df['native-country'] == 'India', 'salary'].value_counts()

salary
<=50K    60
>50K     40
Name: count, dtype: int64

In [152]:
india_high_salary_popular_occupation = df['occupation'].loc[df['native-country'].str.contains('India') & df['salary'].str.contains('>50K')].value_counts()
india_high_salary_popular_occupation.head(1)

occupation
Prof-specialty    25
Name: count, dtype: int64