<a href="https://colab.research.google.com/github/mfernandezzz/Data-Analysis-Projects/blob/main/demographic_data_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Demographic Data Analyzer**

Analyze demographic data from a dataset from the 1994 census database.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv('/content/adult.csv')
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [ ]:
df.shape

(32560, 15)

Assign name columns to the dataset

In [ ]:
col_names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain',
             'capital-loss', 'hours-per-week', 'native-country', 'salary']

df.columns = col_names
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

Each column and his respective datatype

In [ ]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

**How many people of each race are represented in this dataset?**

In [ ]:
df['race'].value_counts()

race
White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [ ]:
xf = pd.Series(df['race'].value_counts())
xf.name = 'Quantity of people per race'
xf.index.name = 'Race'
xf

Race
White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: Quantity of people per race, dtype: int64

In [ ]:
df_race_people = pd.Series([27815, 3124, 1039, 311, 271])

df_race_people.index = [
    'White',
    'Black',
    'Asian-Pac-Islander',
    'Amer-Indian-Eskimo',
    'Other'
]
df_race_people.name = 'Quantity of people per race'
df_race_people.index.name = 'Race'
df_race_people

Race
White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: Quantity of people per race, dtype: int64

**Create a DataFrame with race names, quantity and percentage of people per race.**

In [ ]:
race_percentage = pd.DataFrame({
    'race': ['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other'],
    'quantity': [27815, 3124, 1039, 311, 271]
}, columns = ['race', 'quantity'])

race_percentage['%'] = round(race_percentage['quantity'] * 100 / df.shape[0], 2)
race_percentage

                 race  quantity      %
0               White     27815  85.43
1               Black      3124   9.59
2  Asian-Pac-Islander      1039   3.19
3  Amer-Indian-Eskimo       311   0.96
4               Other       271   0.83

**What is the average age of men?**

In [ ]:
average_age_men = df.loc[df['sex'].str.contains('Male'), 'age'].mean()
f'Average age of men: {round(average_age_men)} years old'

'Average age of men: 39 years old'

**What is the percentage of people who have a Bachelor's degree?**

In [ ]:
df['education'].value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5354
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [ ]:
df_education = pd.DataFrame({
    'education level': ['HS-grad', 'Some-college', 'Bachelors', 'Masters', 'Assoc-voc', '11th', 'Assocc-acdm', '10th', '7th-8th', 'Prof-school', '9th', '12th',
                        'Doctorate', '5th-6th', '1st-4th', 'Preschool'],
    'quantity': [10501, 7291, 5354, 1723, 1382, 1175, 1067, 933, 646, 576, 514, 433, 413, 333, 168, 51]
}, columns = ['education level', 'quantity'])

df_education

   education level  quantity
0          HS-grad     10501
1     Some-college      7291
2        Bachelors      5354
3          Masters      1723
4        Assoc-voc      1382
5             11th      1175
6      Assocc-acdm      1067
7             10th       933
8          7th-8th       646
9      Prof-school       576
10             9th       514
11            12th       433
12       Doctorate       413
13         5th-6th       333
14         1st-4th       168
15       Preschool        51

In [ ]:
bachelors = df_education.loc[df_education['education level'].str.contains('Bachelors'), 'quantity']

total = df_education['quantity'].sum()

bach_percentage = (bachelors * 100) / total
round(bach_percentage, 2)

2    16.44
Name: quantity, dtype: float64

In [ ]:
df_education['%'] = round(df_education['quantity'] * 100 / total, 2)
df_education

   education level  quantity      %
0          HS-grad     10501  32.25
1     Some-college      7291  22.39
2        Bachelors      5354  16.44
3          Masters      1723   5.29
4        Assoc-voc      1382   4.24
5             11th      1175   3.61
6      Assocc-acdm      1067   3.28
7             10th       933   2.87
8          7th-8th       646   1.98
9      Prof-school       576   1.77
10             9th       514   1.58
11            12th       433   1.33
12       Doctorate       413   1.27
13         5th-6th       333   1.02
14         1st-4th       168   0.52
15       Preschool        51   0.16

**What percentage of people with advanced education (Bachelors, Masters, Doctorate) make more than 50k?**

Total of individuals with a salary >50k

In [ ]:
df['salary'].value_counts()

salary
<=50K    24719
>50K      7841
Name: count, dtype: int64

Bachelors with a salary above 50k

In [ ]:
bachelors = df.loc[df['education'].str.contains('Bachelors'), 'salary'].value_counts()
bachelors

salary
<=50K    3133
>50K     2221
Name: count, dtype: int64

Masters with a salary above 50k

In [ ]:
masters = df.loc[df['education'].str.contains('Masters'), 'salary'].value_counts()
masters

salary
>50K     959
<=50K    764
Name: count, dtype: int64

Doctorates with a salary above 50k

In [ ]:
doctorate = df.loc[df['education'].str.contains('Doctorate'), 'salary'].value_counts()
doctorate

salary
>50K     306
<=50K    107
Name: count, dtype: int64

Percentage of individuals with a high level education and a salary above 50k

In [ ]:
# individuals with a salary above 50k
high_salary_total = 7841

# individuals with a high education level and a salary above 50k
high_ed_lvl = 2221 + 959 + 306

percentage = (high_ed_lvl * 100) / high_salary_total
f'Percentage of individuals with advanced education and a salary above 50k: {round(percentage, 2)}%'

'Percentage of individuals with advanced education and a salary above 50k: 44.46%'

**What percentage of people without advanced education make more than 50k?**

In [ ]:
# total of individuals with a salary above 50k - individuals with high level education
low_ed_lvl = high_salary_total - high_ed_lvl

percentage_low = (low_ed_lvl * 100) / high_salary_total

f'Percentage of individuals without advanced education and a salary above 50k: {round(percentage_low, 2)}%'

'Percentage of individuals without advanced education and a salary above 50k: 55.54%'

**What is the minimum and maximum number of hours a person works per week?**

In [ ]:
df['hours-per-week'].min()

1

In [ ]:
df['hours-per-week'].max()

99

**Obtain the education level and the quantity of individuals who works the minimum and maximum hours per week respectively**

In [ ]:
min_hours = df.loc[df['hours-per-week'] == 1, 'education'].value_counts()
min_hours

education
HS-grad         7
Assoc-voc       3
10th            3
Some-college    3
Doctorate       1
9th             1
Masters         1
Assoc-acdm      1
Name: count, dtype: int64

In [ ]:
max_hours = df.loc[df['hours-per-week'] == 99, 'education'].value_counts()
max_hours

education
HS-grad         18
Some-college    14
Bachelors       10
Doctorate        7
Masters          7
7th-8th          7
Prof-school      6
10th             5
Assoc-voc        4
Assoc-acdm       4
9th              1
11th             1
12th             1
Name: count, dtype: int64

**What percentage of people who work the minimum hours per week have a salary of more than 50k?**

Hours per week and the count of people that have a salary >50k working the respective hours

In [ ]:
df.loc[df['salary'].str.contains('>50K'), 'hours-per-week'].value_counts().head()

hours-per-week
40    3247
50    1276
45     685
60     648
55     323
Name: count, dtype: int64

In [ ]:
#example
df.loc[df['hours-per-week'] == 40, 'salary'].value_counts()

salary
<=50K    11969
>50K      3247
Name: count, dtype: int64

Individuals that works the minimum hours per week and have a salary >50k

In [ ]:
df.loc[df['hours-per-week'] == 1, 'salary'].value_counts()

salary
<=50K    18
>50K      2
Name: count, dtype: int64

In [ ]:
min_hours_mask = (df['hours-per-week'] == 1) & (df['salary'].str.contains('>50K'))
df.loc[min_hours_mask]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
188,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K
20071,65,?,76043,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,1,United-States,>50K

In [ ]:
salary_ranges = df['salary'].value_counts()
salary_ranges

salary
<=50K    24719
>50K      7841
Name: count, dtype: int64

In [ ]:
min_hours_percentage = (2 * 100) / 7841
f'Percentage of people that work the minimum hours and have a salary >50k: {round(min_hours_percentage, 2)}%'

'Percentage of people that work the minimum hours and have a salary >50k: 0.03%'

**What percentage of people who works the maximum hours per week have a salary above 50k?**

In [ ]:
df.loc[df['hours-per-week'] == 99, 'salary'].value_counts()

salary
<=50K    60
>50K     25
Name: count, dtype: int64

In [ ]:
max_hours_mask = (df['hours-per-week'] == 99) & (df['salary'].str.contains('>50K'))
# df.loc[max_hours_mask].shape[0]
df_max_hours = df.loc[max_hours_mask]
df_max_hours.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
934,37,Private,176900,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,99,United-States,>50K
1171,25,Private,404616,Masters,14,Married-civ-spouse,Farming-fishing,Not-in-family,White,Male,0,0,99,United-States,>50K
1886,55,Self-emp-not-inc,184425,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,>50K
3577,37,Self-emp-inc,382802,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,99,United-States,>50K
4440,43,Self-emp-inc,286750,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,99,United-States,>50K

In [ ]:
df_max_hours['education'].value_counts()

education
Some-college    6
HS-grad         5
Doctorate       3
Prof-school     3
Bachelors       3
Masters         2
7th-8th         1
Assoc-voc       1
Assoc-acdm      1
Name: count, dtype: int64

In [ ]:
max_hours_percentage = (25 * 100) / 7841
f'Percentage of individuals working the maximum hours and have a salary >50k: {round(max_hours_percentage, 2)}%'

'Percentage of individuals working the maximum hours and have a salary >50k: 0.32%'

In [ ]:
# percentage of people working 40 hours per week with a salary >50k (only for verify)
exam_percentage = (3247 * 100) / 7841
f'Percentage of individuals that works 40 hours per week and have a salary above 50k: {round(exam_percentage, 2)}%'

'Percentage of individuals that works 40 hours per week and have a salary above 50k: 41.41%'

**What country has the highest percentage of people that earn >50k and what is that percentage?**

All the countries in the dataframe

In [ ]:
df['native-country'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

All the countries where individuals have a salary >50k

In [ ]:
df['native-country'].loc[df['salary'].str.contains('>50K')].unique()

array([' United-States', ' India', ' ?', ' South', ' Honduras', ' Canada',
       ' Iran', ' Mexico', ' Cambodia', ' Thailand', ' Taiwan',
       ' Portugal', ' England', ' China', ' Philippines', ' Jamaica',
       ' Germany', ' Japan', ' Italy', ' Dominican-Republic', ' Cuba',
       ' Greece', ' Peru', ' Guatemala', ' El-Salvador', ' France',
       ' Vietnam', ' Poland', ' Puerto-Rico', ' Ireland', ' Yugoslavia',
       ' Columbia', ' Haiti', ' Hong', ' Ecuador', ' Nicaragua',
       ' Trinadad&Tobago', ' Hungary', ' Scotland', ' Laos'], dtype=object)

In [ ]:
countries_high_salary = df['native-country'].loc[df['salary'].str.contains('>50K')].value_counts()
countries_high_salary.tail()

native-country
Dominican-Republic    2
Trinadad&Tobago       2
Nicaragua             2
Laos                  2
Honduras              1
Name: count, dtype: int64

In [ ]:
df_countries_high_salary = pd.DataFrame({
    'country': ['United States', 'Rest of the world', 'Philippines', 'Germany', 'India', 'Canada', 'Mexico', 'England', 'Cuba', 'Italy', 'Japan', 'Taiwan', 'China',
                'Iran', 'South', 'Poland', 'France', 'Puerto Rico', 'Jamaica', 'El Salvador', 'Greece', 'Cambodia', 'Hong Kong', 'Yugoslavia', 'Vietnam', 'Ireland',
                'Portugal', 'Ecuador', 'Haiti', 'Scotland', 'Guatemala', 'Thailand', 'Hungary', 'Colombia', 'Peru', 'Dominican Republic', 'Trinidad and Tobago',
                'Nicaragua', 'Laos', 'Honduras'],
    'quantity': [7171, 146, 61, 44, 40, 39, 33, 30, 25, 25, 24, 20, 20, 18, 16, 12, 12, 12, 10, 9, 8, 7, 6, 6, 5, 5, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 1]
}, columns = ['country', 'quantity'])

df_countries_high_salary.head()

             country  quantity
0      United States      7171
1  Rest of the world       146
2        Philippines        61
3            Germany        44
4              India        40

Verify if the total individuals registered in the DataFrame are equal to the total if individuals with a salary >50k

In [ ]:
df_countries_high_salary['quantity'].sum()

np.int64(7841)

In [ ]:
#create a new column with the percentage of individuals living in his respective country and a salary >50k
#obtain the percentage of individuals with a salary >50k and the respective country
df_countries_high_salary['percentage'] = round(df_countries_high_salary['quantity'] * 100 / 7841, 2)
df_countries_high_salary.head(1)

         country  quantity  percentage
0  United States      7171       91.46

In [ ]:
f'Country with the highest percentage of people that earn >50k: {df_countries_high_salary.iloc[0, 0]}'

'Country with the highest percentage of people that earn >50k: United States'

**Identify the most popular occupation for those who earn >50k in India.**

All the ocupations registered in the DataFrame

In [ ]:
df['occupation'].unique()

array([' Exec-managerial', ' Handlers-cleaners', ' Prof-specialty',
       ' Other-service', ' Adm-clerical', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

Individuals living in India

In [ ]:
df.loc[df['native-country'].str.contains('India')].shape[0]

100

Individuals living in India per range salary

In [ ]:
df.loc[df['native-country'].str.contains('India'), 'salary'].value_counts()

salary
<=50K    60
>50K     40
Name: count, dtype: int64

In [ ]:
india_high_salary_popular_occupation = df['occupation'].loc[df['native-country'].str.contains('India') & df['salary'].str.contains('>50K')].value_counts()
india_high_salary_popular_occupation.head(1)

occupation
Prof-specialty    25
Name: count, dtype: int64

In [ ]:
f'The most popular occupation for those who earns >50k in India: {india_high_salary_popular_occupation.idxmax()}'

'The most popular occupation for those who earns >50k in India:  Prof-specialty'